"""
Pydantic schemas for the AI Factory system.
These enforce strict validation across all agent outputs.
"""

from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field, field_validator
from enum import Enum


class ProjectType(str, Enum):
    WEB_APP = "web_app"
    MOBILE_APP = "mobile_app"
    API = "api"
    DESKTOP = "desktop"
    OTHER = "other"


class Priority(str, Enum):
    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"


class EvaluationStatus(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class DocumentAnalysis(BaseModel):
    """Output from VisionAgent parsing uploaded documents."""
    project_type: ProjectType = Field(default=ProjectType.OTHER, description="Type of project being built")
    features: List[str] = Field(default_factory=list, max_length=25, description="List of key features (max 25)")
    personas: List[str] = Field(default_factory=list, max_length=5, description="User personas (max 5)")
    tech_hints: List[str] = Field(default_factory=list, description="Technology hints from document")
    ambiguities: List[str] = Field(default_factory=list, description="Unclear or ambiguous requirements")
    full_text: str = Field(default="", description="Full extracted text from document")
    
    @field_validator('features')
    @classmethod
    def limit_features(cls, v: List[str]) -> List[str]:
        return v[:25] if len(v) > 25 else v
    
    @field_validator('personas')
    @classmethod
    def limit_personas(cls, v: List[str]) -> List[str]:
        return v[:5] if len(v) > 5 else v


class UserStory(BaseModel):
    """Individual user story generated by PM Agent."""
    id: str = Field(..., pattern=r"^US-\d{3}$", description="Story ID in format US-001")
    title: str = Field(..., min_length=5, max_length=200, description="Brief title for the story")
    user_role: str = Field(..., description="The user persona/role")
    action: str = Field(..., description="What the user wants to do")
    benefit: str = Field(..., description="Why the user wants to do this")
    acceptance_criteria: List[str] = Field(..., min_length=2, max_length=5, description="2-5 acceptance criteria")
    priority: Priority = Field(default=Priority.MEDIUM, description="Story priority")
    
    @field_validator('acceptance_criteria')
    @classmethod
    def validate_criteria_count(cls, v: List[str]) -> List[str]:
        if len(v) < 2:
            raise ValueError("Must have at least 2 acceptance criteria")
        return v[:5] if len(v) > 5 else v


class UserStoriesCollection(BaseModel):
    """Collection of user stories."""
    stories: List[UserStory] = Field(..., min_length=5, max_length=20)


class ScoreBreakdown(BaseModel):
    """Breakdown of PM evaluation scores."""
    requirements: int = Field(..., ge=0, le=30, description="Requirements coverage (0-30)")
    architecture: int = Field(..., ge=0, le=25, description="Architecture soundness (0-25)")
    completeness: int = Field(..., ge=0, le=20, description="Specification completeness (0-20)")
    qa_compliance: int = Field(..., ge=0, le=15, description="QA issue resolution (0-15)")
    security: int = Field(..., ge=0, le=10, description="Security considerations (0-10)")


class PMEvaluation(BaseModel):
    """PM Agent's evaluation of generated specifications."""
    score: int = Field(..., ge=0, le=100, description="Overall score 0-100")
    status: EvaluationStatus = Field(..., description="APPROVED or REJECTED")
    breakdown: ScoreBreakdown = Field(..., description="Score breakdown by category")
    strengths: List[str] = Field(default_factory=list, description="What was done well")
    issues: List[str] = Field(default_factory=list, description="Issues found (if rejected)")
    scolding: str = Field(default="", description="Detailed feedback for rejected specs")
    
    @field_validator('issues')
    @classmethod
    def validate_issues_for_rejection(cls, v: List[str], info) -> List[str]:
        # Issues should be present if status is REJECTED
        return v
    
    @field_validator('scolding')
    @classmethod
    def validate_scolding_for_rejection(cls, v: str, info) -> str:
        # Scolding should be present if status is REJECTED
        return v


class QAIssue(BaseModel):
    """Individual QA issue found during review."""
    id: str = Field(..., description="Issue identifier")
    desc: str = Field(..., description="Description of the issue")
    location: str = Field(..., description="Where the issue was found")


class QAReport(BaseModel):
    """QA Agent's report on specification quality."""
    critical: List[QAIssue] = Field(default_factory=list, description="Critical issues (system crash, data loss, security breach)")
    high: List[QAIssue] = Field(default_factory=list, description="High priority issues (major functionality broken)")
    medium: List[QAIssue] = Field(default_factory=list, description="Medium issues (degraded UX)")
    low: List[QAIssue] = Field(default_factory=list, description="Low priority issues (cosmetic)")
    security_flags: List[str] = Field(default_factory=list, description="Security-specific warnings")


class ClarificationQuestion(BaseModel):
    """Question from DevTeam requiring clarification."""
    id: str = Field(..., description="Question identifier")
    question: str = Field(..., description="The clarification question")
    context: str = Field(default="", description="Why this needs clarification")
    source_agent: str = Field(default="dev_team", description="Which agent asked this")


class ClarificationQuestionsCollection(BaseModel):
    """Collection of clarification questions."""
    questions: List[ClarificationQuestion] = Field(default_factory=list, max_length=10)


class ClarificationAnswer(BaseModel):
    """PM's answer to a clarification question."""
    question_id: str = Field(..., description="ID of the question being answered")
    answer: str = Field(..., description="The answer provided")


class ArchitectureSpec(BaseModel):
    """Tech Lead's architecture specification."""
    tech_stack: Dict[str, str] = Field(default_factory=dict, description="Technology stack choices")
    tech_justification: str = Field(default="", description="Why these technologies were chosen")
    database_schema: str = Field(default="", description="Database schema or description")
    api_design: str = Field(default="", description="API endpoints, methods, payloads")
    security_strategy: str = Field(default="", description="Security approach")
    scalability_plan: str = Field(default="", description="How system scales")
    observability: str = Field(default="", description="Logging, monitoring, alerts")


class BackendSpec(BaseModel):
    """Backend specification from DevTeam."""
    routes: str = Field(default="", description="API routes definition")
    models: str = Field(default="", description="Data models")
    business_logic: str = Field(default="", description="Core business logic")
    error_handling: str = Field(default="", description="Error handling approach")
    environment_vars: List[str] = Field(default_factory=list, description="Required env vars")


class FrontendSpec(BaseModel):
    """Frontend specification from DevTeam."""
    components: str = Field(default="", description="Component structure")
    state_management: str = Field(default="", description="State management approach")
    routing: str = Field(default="", description="Routing configuration")
    styling: str = Field(default="", description="Styling approach")
    error_handling: str = Field(default="", description="Error boundary setup")


class LearnedRule(BaseModel):
    """A rule learned by the Coach agent."""
    date: str = Field(..., description="Date in YYYY-MM-DD format")
    rule: str = Field(..., max_length=150, description="The learned rule (max 150 chars)")
    target_playbook: str = Field(..., description="Which playbook this applies to")
    
    @field_validator('rule')
    @classmethod
    def validate_rule_format(cls, v: str) -> str:
        # Rules should be actionable
        action_words = ['Never', 'Always', 'Ensure', 'Check', 'Verify', 'Include', 'Avoid']
        if not any(word in v for word in action_words):
            # Don't raise error, just log warning - we'll accept it anyway
            pass
        return v[:150] if len(v) > 150 else v


class WorkflowState(BaseModel):
    """Complete workflow state for session persistence."""
    phase: int = Field(default=1, ge=1, le=8, description="Current phase (1-8)")
    retry_count: int = Field(default=0, ge=0, le=3, description="Retry attempts (max 3)")
    context: Optional[DocumentAnalysis] = Field(default=None, description="Parsed document context")
    artifacts: Dict[str, Any] = Field(default_factory=dict, description="Generated artifacts")
    tavily_cache: Dict[str, str] = Field(default_factory=dict, description="Cached Tavily results")
    pm_evaluation: Optional[PMEvaluation] = Field(default=None, description="Last PM evaluation")
    user_stories: List[UserStory] = Field(default_factory=list, description="Generated user stories")
    architecture: Optional[str] = Field(default=None, description="Architecture spec markdown")
    backend_draft: Optional[str] = Field(default=None, description="Backend draft markdown")
    frontend_draft: Optional[str] = Field(default=None, description="Frontend draft markdown")
    qa_report: Optional[QAReport] = Field(default=None, description="QA report")
    backend_final: Optional[str] = Field(default=None, description="Final backend spec")
    frontend_final: Optional[str] = Field(default=None, description="Final frontend spec")
    clarifications: Dict[str, str] = Field(default_factory=dict, description="Answered clarifications")
    previous_scolding: str = Field(default="", description="Previous rejection feedback")
    warnings: List[str] = Field(default_factory=list, description="Accumulated warnings")


class TeamDecision(BaseModel):
    """A decision made by the team through discussion."""
    topic_id: str = Field(..., description="Unique topic identifier")
    topic_name: str = Field(..., description="Human-readable topic name")
    decision: str = Field(..., description="The decision made")
    rationale: str = Field(default="", description="Why this decision was made")
    participants: List[str] = Field(default_factory=list, description="Agents involved")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence level")
    timestamp: str = Field(default="", description="When the decision was made")


class DiscussionState(BaseModel):
    """State of multi-agent discussions for a project."""
    project_id: str = Field(default="default", description="Project identifier")
    decisions: List[TeamDecision] = Field(default_factory=list, description="Decisions made")
    active_topics: List[str] = Field(default_factory=list, description="Topics currently being discussed")
    completed_topics: List[str] = Field(default_factory=list, description="Topics with decisions")
    
    def add_decision(self, decision: TeamDecision) -> None:
        """Record a new decision."""
        self.decisions.append(decision)
        if decision.topic_id in self.active_topics:
            self.active_topics.remove(decision.topic_id)
        if decision.topic_id not in self.completed_topics:
            self.completed_topics.append(decision.topic_id)
    
    def get_decision(self, topic_id: str) -> Optional[TeamDecision]:
        """Get decision for a specific topic."""
        for d in self.decisions:
            if d.topic_id == topic_id:
                return d
        return None
    
    def has_decision(self, topic_id: str) -> bool:
        """Check if a topic has been decided."""
        return topic_id in self.completed_topics


# Helper functions for schema validation
def validate_json_to_schema(json_str: str, schema_class: type) -> tuple[bool, Any, str]:
    """
    Validate JSON string against a Pydantic schema.
    Returns (success, parsed_object_or_none, error_message)
    """
    import json
    try:
        data = json.loads(json_str)
        obj = schema_class.model_validate(data)
        return True, obj, ""
    except json.JSONDecodeError as e:
        return False, None, f"JSON parsing error: {str(e)}"
    except Exception as e:
        return False, None, f"Validation error: {str(e)}"


def safe_parse_llm_json(response: str, schema_class: type) -> tuple[bool, Any, str]:
    """
    Safely parse LLM response that might contain JSON within markdown code blocks.
    """
    import json
    import re
    
    # Try to extract JSON from markdown code blocks
    json_patterns = [
        r'```json\s*([\s\S]*?)\s*```',
        r'```\s*([\s\S]*?)\s*```',
        r'\{[\s\S]*\}'
    ]
    
    for pattern in json_patterns:
        matches = re.findall(pattern, response)
        for match in matches:
            json_str = match.strip()
            if json_str.startswith('{') or json_str.startswith('['):
                success, obj, error = validate_json_to_schema(json_str, schema_class)
                if success:
                    return True, obj, ""
    
    # Last resort: try the whole response
    return validate_json_to_schema(response.strip(), schema_class)
